#!/usr/bin/env bash
# generate_secrets.sh — Auto-generate .env with strong random secrets.
# Usage: ./generate_secrets.sh
set -euo pipefail

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
  echo "⚠  .env already exists. To regenerate, delete it first:"
  echo "   rm $ENV_FILE && ./generate_secrets.sh"
  exit 1
fi

SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")
DB_PASSWORD=$(python3 -c "import secrets; print(secrets.token_urlsafe(24))")

cat > "$ENV_FILE" <<EOF
# Generated by generate_secrets.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Keep this file private — never commit it to version control.

SECRET_KEY=${SECRET_KEY}
DB_PASSWORD=${DB_PASSWORD}
TZ=UTC
MAX_UPLOAD_MB=16
DB_POOL_SIZE=10
DB_MAX_OVERFLOW=20
EOF

echo "✅  .env created with strong random secrets."
echo ""
echo "Next steps:"
echo "  1. Edit .env to set TZ, MAX_UPLOAD_MB, etc."
echo "  2. Run: docker compose up -d"
